version: "3"
services:
  bedrockconnect:
    build: ./bedrockconnect
    ports:
      - "19132:19132/udp"
  bind9:
    build: 
      context: ./bind9
      args: 
        BCIP: 104.238.130.180
        NSIP: 104.238.130.180
    ports: 
      - "53:53/udp"
